name: ENV-CONTEXT
on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'Trainee Name'
        default: 'Niraj'
        required: false
        type: string


jobs:
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the training session number
        run: |
          echo 'Hi ${{ inputs.username }}'
          echo 'you attending Session-number: ${{ vars.actions }}'
          echo "Session conducted by :" ${{env.name}}
        env:
          NAME: karthika

      - name: Check job status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Job succeeded"
          else
            echo "Job failed"
          fi
