name: ENV-CONTEXT
on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'Trainee Name'
        default: 'Niraj'
        required: false
        type: string

jobs:
  linux_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        session: [1, 2]
    steps:
      - name: Print the training session number
        run: |
          echo 'Hi ${{ inputs.username }}'
          echo 'You are attending Session-number: ${{ vars.actions }}'
          echo "Session conducted by: ${{ env.NAME }}"
          echo "Number session: ${{ matrix.session }}"
          echo "Credetials for the training" : ${{env.access_cred}}
          echo "name of the os:" ${{runner.os}}
        env:
          NAME: karthika
          access_cred: ${{secrets.API_KEY}}

      - name: Check job status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Job succeeded"
          else
            echo "Job failed"
          fi
