name: ENV-CONTEXT
on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the training session number
        run: |
          echo 'Hi ${{ env.NAME }}'
          echo 'Session-number: ${{ env.env_var }}'
        env:
          NAME: harish

      - name: Check job status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Job succeeded"
          else
            echo "Job failed"
          fi
