name: ENV-CONTEXT
on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'Trainee Name'
        default: 'Niraj'
        required: false
        type: string
      ODC:
        description: 'Types environments'
        default: 'DEV'
        required: True
        type: environment

jobs:
  linux_job:
    runs-on: Linux
    environment: ${{inputs.ODC}}
    outputs:
      output1: ${{ steps.demo.outputs.test }}
    strategy:
      matrix:
        session: [1, 2]
    steps:
      - name: Print the training session number
        id: demo
        run: |
          echo 'Hi ${{ inputs.username }}'
          echo 'You are attending Session-number: ${{ vars.actions }}'
          echo "Session conducted by: ${{ env.NAME }}"
          echo "Number session: ${{ matrix.session }}"
          echo "Credentials for the training: ${{ env.access_cred }}"
          echo "Name of the OS: ${{ runner.os }}"
          echo "test=welcome to the training" >> "$GITHUB_OUTPUT"
          echo "Conducted on:" ${{vars.ODC}}
        env:
          NAME: karthika
          access_cred: ${{ secrets.API_KEY }}
  
      - name: Check job status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Job succeeded"
          else
            echo "Job failed"
          fi
