name: ENV-CONTEXT
on: push
env:
  NAME: ABHSHEK
  env_var: ${{ vars.ACTIONS }}

jobs:
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the training session number
        run: |
          echo 'Hi ${{ env.NAME }}'
          echo 'Session-number: ${{ env.env_var }}'
        env:
          NAME: harish
 
      - name: Check job status
        run: |
          if [ "${{ job.linux_job.status }}" == "success" ]; then
            echo "Job succeeded"
          else
            echo "Job failed"
          fi
