name: ENV-CONTEXT
on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
      # env_var: ${{ vars.ACTIONS }}

jobs:
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the training session number
        run: |
          echo 'Hi ${{ inputs.username }}'
          echo 'you attending Session-number: ${{ env.env_var }}'
          echo Session conducted by : '$env.name'
        env:
          NAME: karthika

      - name: Check job status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Job succeeded"
          else
            echo "Job failed"
          fi
